Models/ErrorViewModel.cs
using System;

namespace tp7.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EscapeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using tp7.Models;

namespace tp7.Controllers
{
    public class EscapeController : Controller
    {
        private readonly ILogger<EscapeController> _logger;

        public IActionResult checkResult(string clave, string respuesta, string urlActual, string nuevaUrl)
        {
            ViewBag.Error = null;

            if(clave == respuesta){
                return Redirect(nuevaUrl);
            }else if (clave != ""){
                ViewBag.Error = "Clave incorrecta";
            }

            return View(urlActual);
        }

        public EscapeController(ILogger<EscapeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        // [HttpPost]
        public IActionResult Habitacion1(string clave="")
        {
            if(clave != ""){
                return this.checkResult(clave, "how to sell drugs online", "Habitacion1", "Habitacion2");
            }

            return View("Habitacion1");
        }

        // [HttpPost]
        public IActionResult Habitacion2(string clave="")
        {
            if(clave != ""){
                return this.checkResult(clave, "rick", "Habitacion2", "Habitacion3");
            }

            return View("Habitacion2");
        }

        // [HttpPost]
        public IActionResult Habitacion3(string clave="")
        {
            if(clave != ""){
                return this.checkResult(clave, "black mirror", "Habitacion3", "Habitacion4");
            }

            return View("Habitacion3");
        }
        // [HttpPost]
        public IActionResult Habitacion4(string clave="")
        {
            if(clave != ""){
                return this.checkResult(clave, "los 100", "Habitacion4", "Victoria");
            }

            return View("Habitacion4");
        }

        public IActionResult Victoria()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using tp7.Models;

namespace tp7.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Tutorial()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Escape/Habitacion1.cshtml
@{
    ViewData["Title"] = "Habitacion 1";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-6">
        <img width="100%" src="~/img/htsd.jpeg" draggable="false" class="rounded" />
    </div>

    <div class="col-6">

        <div id="pista" class="d-none mb-5">
            <h3>Pista</h3>
            <p>Es un adolescente que comienza a vender éxtasis por internet y se convierte en uno de los traficantes más grandes de Europa para recuperar a su exnovia</p>
        </div>

        <div>
            <h4>Ingrese el título de la serie</h4>

            <form method="POST" action='@Url.Action("Habitacion1", "Escape")'>
                <div class="form-group">
                    <input name="clave" autocomplete="off">
                </div>

                <div class="d-flex">
                    <button class="btn btn-success">Comprobar</button>
                    <button onclick="$('#pista').removeClass('d-none')" type="button" class="btn btn-clave btn-danger mx-2">Pista</button>
                </div>
            </form>
        </div>
    </div>
</div>

@{
    if( ViewBag.Error == "Clave incorrecta" ){
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script src="~/js/swal/error.js"></script>
    }
}

Views/Escape/Habitacion2.cshtml
@{
    ViewData["Title"] = "Habitacion 2";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-6">
        <img width="100%" src="~/img/rick.jpg" draggable="false" class="blur rounded" />
    </div>

    <div class="col-6">
        <div id="pista" class="d-none mb-5">
            <h3>Pista</h3>
            <p>"Te diré lo que pienso sobre la escuela, Jerry: es una pérdida de tiempo. Montón de gente corriendo alrededor chocando uno con el otro. Tipo enfrente diciendo «dos más dos» y la gente atrás dice «cuatro». Luego la campana suena y te dan un cartón de leche y un pedazo de papel que dice que puedes hacer del baño o algo. Digo, no es lugar para gente inteligente, Jerry. Sé que no es opinión popular, pero esos son mis dos centavos sobre el asunto"</p>
        </div>

        <div>
            <h4>Ingrese el nombre del personaje </h4>

            <form method="POST" action='@Url.Action("Habitacion2", "Escape")'>
                <div class="form-group">
                    <input name="clave" autocomplete="off">
                </div>

                <div class="d-flex">
                    <button class="btn btn-success">Comprobar</button>
                    <button onclick="$('#pista').removeClass('d-none')" type="button" class="btn btn-clave btn-danger mx-2">Pista</button>
                </div>
            </form>
        </div>
    </div>



</div>

Views/Escape/Habitacion3.cshtml
@{
    ViewData["Title"] = "Habitacion 3";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-6">
        <img width="100%" src="~/img/black-mirror.jpg" draggable="false" class="blur rounded" />
    </div>

    <div class="col-6">
        <div id="pista" class="d-none mb-5">
            <h3>Pista</h3>
            <p>La serie está basada en contar distopías posibles y cercanas según las amenazas existen a nuestro alrededor: la obsesión por las redes sociales, la inteligencia artificial, la acumulación de datos sobre nuestra vida, entre otras.</p>
        </div>

        <div>
            <h4>Ingrese el título de la serie</h4>

            <form method="POST" action='@Url.Action("Habitacion3", "Escape")'>
                <div class="form-group">
                    <input name="clave" autocomplete="off">
                </div>

                <div class="d-flex">
                    <button class="btn btn-success">Comprobar</button>
                    <button onclick="$('#pista').removeClass('d-none')" type="button" class="btn btn-clave btn-danger mx-2">Pista</button>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Escape/Habitacion4.cshtml
@{
    ViewData["Title"] = "Habitacion 4";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-6">
        <img width="100%" src="~/img/100.jpg" draggable="false" class="blur rounded" />
    </div>

    <div class="col-6">
        <div id="pista" class="d-none mb-5">
            <h3>Pista</h3>
            <p>Son detenidos juveniles son enviados a la Tierra en un último intento de determinar si es habitable. Descubren que algunos sobrevivieron al apocalipsis: los terrestres, que viven en clanes encerrados en una lucha de poder; los Grounders, otro grupo de terrestres que los Montañeses han convertido en caníbales; y los Montañeses, que viven en el Monte Weather, descendientes de aquellos que se encerraron antes del apocalipsis. Bajo el liderazgo de Bellamy y Clarke, los jóvenes intentan sobrevivir en las duras condiciones de la superficie, luchar contra los terrestres hostiles y establecer comunicación con el Arca.</p>
        </div>

        <div>
            <h4>Ingrese el título de la serie</h4>

            <form method="POST" action='@Url.Action("Habitacion4", "Escape")'>
                <div class="form-group">
                    <input name="clave" autocomplete="off">
                </div>

                <div class="d-flex">
                    <button class="btn btn-success">Comprobar</button>
                    <button onclick="$('#pista').removeClass('d-none')" type="button" class="btn btn-clave btn-danger mx-2">Pista</button>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Escape/Index.cshtml
@{
    ViewData["Title"] = "Sala de Escape";
}
<div class="container">
    <div class="text-center">
        <h1 class="display-4">Bienvenido a la sala de escape </h1>
    </div>

    <a asp-area="" asp-controller="Escape" asp-action="Habitacion1" class="btn btn-clave btn-danger">Comenzar</a>
</div>

Views/Escape/Victoria.cshtml
@{
    ViewData["Title"] = "Victoria";
}


<div class="text-center">
    <h1>¡Victoria!</h1>
    <h4>¡Felicitaciones, completaste correctamente la sala de escape!</h4>
    <img src="~/img/victoria.gif" />
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">

<div class="text-center">
    <h1 class="display-4">Sala de escape Netflix</h1>
</div>
<div class="row justify-content-center">
    <div class="col-8 ">
        <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="~/img/bad.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/img/elite.jpg" class="d- w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/img/ozark.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/img/papel.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/img/peaky.jpg" class="d-block w-100" alt="...">
                </div>
            </div>
        </div>
    </div>
</div>

</div>

Views/Home/Tutorial.cshtml
@{
    ViewData["Title"] = "Tutorial";
}
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <h1>@ViewData["Title"]</h1>
    
            <h4>
                Bienvenidos al tutorial de la sala de escape, en este tutorial te enseñaremos
                como funciona y como jugar a nuestro increible juego.<br>
    
                En la sala de escape se te mostraran una serie de preguntas
                de las cuales tendras que escribir sus respuestas
                para conseguir pasar de sala, si contestas correctamente
                podras pasar a la proxima sala, de no ser asi repetiras el nivel.<br>
                A continuacion te mostraremos una serie de imagenes
                con las cuales te podras guiar.
            </h4>
        </div>    
    </div>
    <div class="row justify-content-center">
        <div class="col-6">
            <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="~/img/h1.png" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="~/img/h2.png" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="~/img/h3.png" class="d-block w-100" alt="...">
                        </div>
                </div>
            </div>

        </div>
    
    </div>
    
    <a href="../Escape" class="btn btn-clave btn-danger mt-3">Comenzar a jugar</a>
    
</div>
   
    

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sala de escape</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-gradient navbar-color border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sala de escape</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Tutorial">Tutorial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Escape" asp-action="Index">Jugar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> *@
        <nav style="background:black;" class="navbar navbar-expand-lg navbar-gradient navbar-dark fixed-top py-3">
            <div class="container-fluid px-md-5 px-3">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/logo.png" width="200px" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse ml-5">
                 <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link font-semibold" asp-area="" asp-controller="Home" asp-action="Tutorial">Tutorial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-semibold" asp-area="" asp-controller="Escape" asp-action="Index">Jugar</a>
                        </li>
                    </ul>
                    <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link font-semibold" href="index.html">Inicio</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link font-semibold" href="#">Series</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link font-semibold" href="#">Películas</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link font-semibold" href="#">Novedades populares</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link font-semibold" href="#">Mi lista</a>
                        </li>
                    </ul> -->

                    <div class="d-flex align-items-center">
                        <i class="fas fa-search m-0 mx-3"></i>
                        <i class="fas fa-gift m-0 mx-3"></i>
                        <i class="fas fa-bell m-0 mx-3"></i>
                        
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div class="container" style="margin-top:100px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - tp7 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/header.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>